[package]
name = "blake3_merkle"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"

[dev-dependencies]
rand = "0.8.5"
